# .github/workflows/build.yml
name: Build


# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  pull_request:
    branches: 
        - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  before_install:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build
        run: |
          sudo apt update
          sudo apt install -y g++-8 gcc-8 colordiff coreutils graphviz inkscape make git unzip cmake
          source ./.github/../travis/common.sh
          stdbuf -i0 -o0 -e0 ./.github/../.travis/fixup-git.sh
          source ./.github/../travis/common.sh
          bash ./.github/../travis/install.sh
  script:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: run_script
        run: |
          bash ./.github/../travis/script.sh

